# Development environment
name: torch_v2_3

# Putting many channels makes creation of env very slow :(
channels:
  - conda-forge
  - pytorch
  - nvidia
  - nodefaults

dependencies:
  - python>=3.10
  - ipdb                  # Interactive debugging
  - ipykernel             # Make kernel available to Jupyter environment
  - packaging             # To parse package versions
  - memory_profiler
  - numpy>=1.26
  - scipy>=1.11
  - pandas>=2.1
  - pyarrow>=15.0         # Pandas runs, but complains without this
  - matplotlib>=3.8
  - plotly>=5.15
  - python-kaleido>=0.2
  - nibabel>=5.0
  - h5py>=3.10
  - scikit-learn>=1.3
  - scikit-image>=0.22
  - opencv>=4.8
  - monai>=1.1
  - pytorch=2.3
  - torchvision>=0.18
  - cudatoolkit>=11.4
    # - pytorch-cuda=11.8
  - torchmetrics>=1.2
  - tensorboard>=2.14
  - yacs                  # Simple experiment configuration system
  - tqdm>=4.38
  - pip
  - pip:
    - PyYAML
    - bm3d
    - torch_optimizer
    - pytorch-wavelets


# Create environment with
# conda env create -f conda_torch_v2_3.yml

# Update environment (e.g. if new package required)
# conda env update --file conda_torch_v2_3.yml --prune

# Activate environment with
# conda activate torch_v2_3

# List all available environments
# conda env list

# Remove environment with
# conda remove --name torch_v2_3 --all
