seed: 7

runtype: train
# runtype: test

path_to_outputs: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_11_20

# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol/2024-11-15_15h30m00s/checkpoints/epoch_0499.pt  # TODO: SET (OR LEAVE COMMENTED).

dataset:
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/
  n_volumes: 5
  n_slices: 2
  with_mask: False  # NOTE: During inference phase, set to True.
  acceleration: 4
  center_frac: 0.15

dataloader:
  effective_batch_size: 720_000

model:
  id: Siren
  params:
    coord_dim: 4
    vol_embedding_dim: 256
    coil_embedding_dim: 64
    hidden_dim: 512
    levels: 5
    n_min: 45
    size_hashtable: 12
    n_layers: 6

loss:
  id: MSEL2
  params:
    gamma: 0.0
    sigma: 0.1

optimizer:
  id: Adam
  params:
    lr: 5.e-6 # The dot is necessary, otherwise the parser will mistake this for a string (and not a float).

scheduler:
  id: StepLR
  params:
    gamma: 1.0
    step_size: 20_000

# Training Process
n_epochs: 1000
log_interval: 100
checkpoint_interval: 1000  # Keep in mind that each checkpoint takes ~241 MB of space.


###################################################
# INFORMATION ONLY - NO EFFECT ON RUN
###################################################
# The following section is for documentation purposes only.
# It does not affect the actual behavior of the run.
# These values are used solely for Tensorboard output, to help identify run types.
hparam_info:
  # dataset: "undersampled (except center)"
  dataset: "all data (except center)"

  observation_type: "train sample"
  # observation_type: "test sample"

  # regularization: "None"
  # regularization: "layer norm"
  # regularization: "weight norm"
  # regularization: "AdamW (weight decay)"

  # normalization: "None"
  normalization: "divide by .999 abs quantile"
  # normalization: "divide by max modulus"
  # normalization: ".05 / .95 real and imag parts"
  # normalization: "min/max real and imag parts"